### ISSUE TITLE
[CONFIGURATION]: Generate a Runnable JAR File Using MAVEN

### ISSUE THREAD

**Issue by profpantoja** [profpantoja/chonGame#33]
É preciso permitir que a engine gere o JAR executável do projeto com as dependências.

- **Usando o MAVEN**: tentamos executar fazendo os seguintes passos:
> Adicionando a main class chon.group.Engine em: 
  ```
            <plugin>
                <groupId>org.openjfx</groupId>
                <artifactId>javafx-maven-plugin</artifactId>
                <version>0.0.6</version>
                <executions>
                    <execution>
                        <!-- Default configuration for running -->
                        <!-- Usage: mvn clean javafx:run -->
                        <id>default-cli</id>
                        <configuration>
                            <mainClass>chon.group.Engine</mainClass>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
  ```
> Adicionando o plugin do shade do MAVEN para incluir todas as dependências:
```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version> <!-- Replace with the latest version -->
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <!-- Add the Main-Class to the manifest -->
                                <transformer
                                    implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>chon.group.Engine</mainClass> <!-- Replace with your
                                    main class -->
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
 ```

> O comando via terminal a executar é esse, mudando o endereço local do openjfx
  ```
$ java --module-path /usr/share/openjfx/lib/ --add-modules javafx.controls,javafx.fxml -jar chon-game.jar 
  ```

> O comando no terminal do VSCode é
  ```
mvn package
mvn clean package
  ```

Daí o JAR é gerado na pasta target do projeto.

> Ao tentar executar o arquivo, gera o seguinte erro:
  ```
$ java --module-path /usr/share/openjfx/lib/ --add-modules javafx.controls,javafx.fxml -jar chon-game.jar 
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
        at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:222)
        at javafx.graphics/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:261)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:267)
        at javafx.graphics/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:158)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:658)
        at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:409)
  ```

- **javafx.fxml**: inserir essa dependência no pom.xml faz a engine não rodar (gera um erro).

**Comment by vitorhub182** [comment]
As libs do javafx devem baixadas à parte. 

Local para baixar a lib do javafx: https://gluonhq.com/products/javafx/
(Baixem o "Type: SDK" e o sistema operacional fica a sua escolha)

Extraiam manualmente e enviem a pasta para o diretório de instalação do java.

mvn package
mvn clean package

Comando generico: java --module-path <caminho_ate_a_lib_javafx> --add-modules javafx.controls,javafx.fxml -jar .\game-1.jar

Comando funcional no windows: java --module-path "C:\Program Files\Java\javafx-sdk-23.0.2\lib"  --add-modules javafx.controls,javafx.fxml -jar .\game-1.jar
